@startuml
actor Gamer as g
participant GameS as gs
participant GameProcD as gpd
participant GameCredD as gcd
participant GameStoreD as gsd

== show game menu ==
g -> gs: show menu
alt entered game? contains [uuid]
    gs -> gpd: check stage[player]
    gpd -> gs: check stage ok[player]
    gs -> g: show menu items ok[uuid][items]
else not entered game. not contains [uuid]
    gs -> g: show menu items ok[items]
end

== register new player ==
g -> gs: register
gs -> gcd: register[user]
gcd -> gs: register ok[player]
gs -> g: register ok

== enter game ==
g -> gs: enter game[user]
gs -> gcd: get player[user]
gcd -> gs: get player ok[player]
gs -> gpd: connect player[player][uuid]
gs -> gpd: load game or create new
gpd -> gsd: have player saved game
alt player have saved game
    ... load saved game action ...
else player doesn't have saved game
    ... start new game action ...
end
gs -> g: enter game ok[uuid]

== load game ==
g -> gs: load saved game[uuid]
gs -> gpd: load saved game[uuid]
gpd -> gsd: get saved game[player]
alt have saved game
    gsd -> gpd: saved game[splayer]
    gpd -> gpd: load player from save[splayer]
    gpd -> gpd: load map from save[splayer]
    gpd -> gs: load saved game ok[player]
    gs -> g: load saved game ok[uuid]
else don't have saved game
    gpd -> gs: load saved game fail[player]
    gs -> g: load saved game fail[uuid]
end

== start new game ==
g -> gs: start new game[uuid]
gs -> gpd: generate new map[player]
gpd -> gpd: place entities
gpd -> gpd: place enemies
gpd -> gpd: place player
gpd -> gpd: save player and his map[player][map]
gpd -> gs: generate new map ok[player][map]
gs -> g: start new game ok[uuid]

== save game ==
g -> gs: save game[uuid]
gs -> gpd: save game[player]
gpd -> gsd: save player[player]
gpd -> gsd: save player map[player][map]
gpd -> gs: save game ok[player]
gs -> g: save game ok[uuid]

== show map, accessed when game end ==
g -> gs: get full map[uuid]
gs -> gpd: get map[player]
gpd -> gs: get map ok[player][map]
gs -> g: get my map ok[uuid][map]
g -> g: gamer execute map.show[map]

== enemies near (1 step) ==
g -> gs: get enemies near[uuid]
gs -> gpd: get enemies near[player]
gpd -> gpd: get player pos[player][pos]
gpd -> gpd: get player map[player][map]
gpd -> gpd: get enemies near[player][map]
gpd -> gs: get enemies near ok[player][enemies]
gs -> g: get enemies near ok[uuid][enemies]

== movement ==
g -> gs: move to[uuid][vector]
gs -> gpd: move to[player][vector]
gpd -> gpd: check busy pos[player][vector]
alt not busy pos case
    gpd -> gpd: update player pos[player][new_pos]
    gpd -> gs: move to ok[player]
    gs -> g: move to ok[uuid]
else pos contains chest or trap
    alt found chest case
        gpd -> gpd: check health player[player]
        alt player don't have 100% health
            gpd -> gpd: [chest] generate health restore
            gpd -> gpd: restore player health by chest[player][chest]
        end
        gpd -> gpd: action [found trap or chest]
        gpd -> gs: move to ok[player]
        gs -> g: move to ok[uuid]
    else found trap case
        gpd -> gpd: [trap] generate damage
        gpd -> gpd: attack player [player]
        gpd -> gpd: check end game[player][end_game]
        alt end game
            gpd -> gs: move to fail[player][end_game]
            gs -> g: move to fail[uuid][end_game]
        else
            gpd -> gpd: action [found trap or chest]
            gpd -> gs: move to ok[player]
            gs -> g: move to ok[uuid]
        end
    end
else pos is busy
    gpd -> gs: move to fail[player]
    gs -> g: move to fail[uuid]
end

== attack enemies ==
g -> gs: attack pos[uuid][vector]
gs -> gpd: attack pos[player][vector]
gpd -> gpd: check enemy from player pos[player][vector]
alt enemy detect case
    gpd -> gpd: get enemy[enemy_pos]
    gpd -> gpd: attack scene[player][enemy]
    gpd -> gpd: update player stats[player]
    gpd -> gpd: update player pos[player][enemy_pos]
    gpd -> gpd: check end game[player][end_game]
    alt end game
        gpd -> gs: attack pos fail[player][end_game]
        gs -> g: attack pos fail[uuid][end_game]
    else
        gpd -> gs: attack pos ok[player]
        gs -> g: attack pos ok[uuid][player_changed_stats]
    end
else no enemy detect case
    gpd -> gs: attack pos fail[player]
    gs -> g: attack pos fail[uuid]
end

== end game by player dead ==
... all actions in ...
g -> gs: any action[uuid]
gs -> g: fail send[uuid][end_game]

@enduml